apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jf9d6pr9a-java-quarkus
  janus-idp.io/tekton: jf9d6pr9a-java-quarkus
  backstage.io/kubernetes-id: jf9d6pr9a-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jf9d6pr9a-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
